# Generated by Django 4.1.7 on 2023-04-14 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('ожидание ответа', 'Ожидание ответа'), ('не интересует', 'Не интересует'), ('свяжусь в ближайшее время', 'Свяжусь в ближайшее время'), ('готов дать ответ через неделю', 'Готов дать ответ через неделю'), ('готов дать ответ через месяц', 'Готов дать ответ через месяц'), ('заинтересован', 'Заинтересован')], default='ожидание ответа', max_length=128, verbose_name='статус')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='название')),
                ('position', models.CharField(max_length=256, verbose_name='должность')),
                ('salary', models.PositiveIntegerField(verbose_name='зарплата')),
                ('remote', models.BooleanField(default=False, verbose_name='удаленная')),
                ('country', models.CharField(max_length=256, verbose_name='страна')),
                ('city', models.CharField(max_length=256, verbose_name='город')),
                ('is_closed', models.BooleanField(default=False, verbose_name='закрыто')),
                ('description', models.CharField(max_length=2048, verbose_name='описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='отредактировано')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.companyprofile', verbose_name='компания')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='название')),
                ('position', models.CharField(max_length=256, verbose_name='должность')),
                ('salary', models.PositiveIntegerField(verbose_name='зарплата')),
                ('relocate', models.BooleanField(default=False, verbose_name='возможность переезда')),
                ('remote', models.BooleanField(default=False, verbose_name='удаленная')),
                ('visible', models.BooleanField(default=False, verbose_name='видимость')),
                ('is_draft', models.BooleanField(default=False, verbose_name='черновик')),
                ('description', models.TextField(max_length=2048, verbose_name='описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='отредактировано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(verbose_name='сопроводительное письмо')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.resume', verbose_name='резюме')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.status', verbose_name='статус')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.vacancy', verbose_name='вакансия')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(verbose_name='сопроводительное письмо')),
                ('date', models.DateTimeField(verbose_name=models.DateTimeField(auto_now_add=True, verbose_name='дата'))),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.resume', verbose_name='резюме')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.status', verbose_name='статус')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.vacancy', verbose_name='вакансия')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=256, verbose_name='должность')),
                ('description', models.CharField(max_length=2048, verbose_name='описание')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.companyprofile', verbose_name='компания')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.resume', verbose_name='резюме')),
            ],
            options={
                'verbose_name': 'Опыт работы',
                'verbose_name_plural': 'Опыт работы',
            },
        ),
    ]
