# Generated by Django 4.1.7 on 2023-04-11 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('ожидание ответа', 'Ожидание ответа'), ('не интересует', 'Не интересует'), ('свяжусь в ближайшее время', 'Свяжусь в ближайшее время'), ('готов дать ответ через неделю', 'Готов дать ответ через неделю'), ('готов дать ответ через месяц', 'Готов дать ответ через месяц'), ('заинтересован', 'Заинтересован')], default='ожидание ответа', max_length=128, verbose_name='статус')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(verbose_name='сопроводительное письмо')),
                ('date', models.DateTimeField(verbose_name=models.DateTimeField(auto_now_add=True, verbose_name='дата'))),
                ('resume_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.resume', verbose_name='резюме')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.status', verbose_name='статус')),
                ('vacancy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.vacancy', verbose_name='вакансия')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(verbose_name='сопроводительное письмо')),
                ('date', models.DateTimeField(verbose_name=models.DateTimeField(auto_now_add=True, verbose_name='дата'))),
                ('resume_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.resume', verbose_name='резюме')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.status', verbose_name='статус')),
                ('vacancy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.vacancy', verbose_name='вакансия')),
            ],
        ),
    ]
