# Generated by Django 4.1.7 on 2023-04-18 10:39

from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = []
