# Generated by Django 4.1.7 on 2023-04-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20230418_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='title',
            field=models.CharField(choices=[('ожидание ответа', 'Ожидание ответа'), ('принято', 'Приглашение'), ('отказ', 'Отказ')], default='ожидание ответа', max_length=128, verbose_name='статус'),
        ),
    ]
