# Generated by Django 4.1.7 on 2023-04-12 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_response_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='status_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.status', verbose_name='статус'),
        ),
    ]
