# Generated by Django 4.1.7 on 2023-04-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_response_status_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата'),
        ),
    ]
