# Generated by Django 4.1.7 on 2023-04-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_offer_options_alter_status_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
