# Generated by Django 4.1.7 on 2023-03-21 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='название')),
                ('position', models.CharField(max_length=256, verbose_name='должность')),
                ('salary', models.PositiveIntegerField(verbose_name='зарплата')),
                ('remote', models.BooleanField(default=False, verbose_name='удаленная')),
                ('country', models.CharField(max_length=256, verbose_name='страна')),
                ('city', models.CharField(max_length=256, verbose_name='город')),
                ('is_closed', models.BooleanField(default=False, verbose_name='закрыто')),
                ('description', models.CharField(max_length=2048, verbose_name='описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='отредактировано')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyapp.company', verbose_name='компания')),
            ],
        ),
    ]
