# Generated by Django 4.1.7 on 2023-03-22 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_companyprofile_is_partner'),
        ('companyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.companyprofile', verbose_name='компания'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
