# Generated by Django 4.1.7 on 2023-04-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklinkuser',
            name='moderator',
            field=models.BooleanField(default=False),
        ),
    ]
