# Generated by Django 4.1.7 on 2023-03-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_alter_companyprofile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='is_partner',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
