# Generated by Django 4.1.7 on 2023-03-27 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_joblist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobList',
        ),
    ]
